# AUTOGENERATED! DO NOT EDIT! File to edit: app.ipynb.

# %% auto #0
__all__ = ['learn', 'categories', 'image', 'label', 'examples', 'intf', 'is_cat', 'classify_image']

# %% app.ipynb #cf4081fe
from fastai.vision.all import *
import gradio as gr

# Patch retain_type in all the places it's used
# def _patched_retain_type(x, old=None, typ=None):
#     try:
#         if typ is None and old is not None:
#             typ = type(old)
#         if typ is None:
#             return x
#         return typ(x)
#     except Exception:
#         return x

# Inject into the module's globals so the local reference is replaced
# ft_module.__dict__['retain_type'] = _patched_retain_type

def is_cat(x): return x[0].isupper()


# %% app.ipynb #34dbc0b7
learn = load_learner('model.pkl')


# %% app.ipynb #b6661c98
categories = ('Dog', 'Cat')
# def classify_image(img):
#     import logging
#     logging.warning(f"TYPE: {type(img)}")
#     logging.warning(f"VALUE: {img}")
#     if isinstance(img, str):
#         pred, idx, probs = learn.predict(PILImage.create(img))
#     elif isinstance(img, dict):
#         logging.warning(f"DICT KEYS: {img.keys()}")
#         # try to extract image from dict
#         actual_img = img.get('path') or img.get('composite') or img.get('image') or list(img.values())[0]
#         logging.warning(f"ACTUAL IMG TYPE: {type(actual_img)}")
#         pred, idx, probs = learn.predict(PILImage.create(actual_img))
#     else:
#         pred, idx, probs = learn.predict(PILImage.create(img))
#     return dict(zip(categories, map(float, probs)))

def classify_image(img):
    pred, idx, probs = learn.predict(PILImage.create(img))
    return dict(zip(categories, map(float, probs)))


# %% app.ipynb #bdfb0d35
image = gr.Image(type="filepath")
label = gr.Label()
examples = ['dog.jpg', 'cat.jpg', 'dunno.jpg']

intf = gr.Interface(fn=classify_image, inputs=image, outputs=label, examples=examples, cache_examples=False)
intf.launch()

